// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 29 Oct 2018 22:41:05 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void cb_string_ebc8845d(unsigned int cmd_handle, unsigned int error_code, char* str_value) {
	callback_stringEBC8845D(cmd_handle, error_code, str_value);
}

void cb_int_a42ee42d(unsigned int cmd_handle, unsigned int error_code, unsigned int int_value) {
	callback_intA42EE42D(cmd_handle, error_code, int_value);
}

void cb_int_string_f8ca4bd5(unsigned int cmd_handle, unsigned int error_code, unsigned int int_value, char* str_value) {
	callback_int_stringF8CA4BD5(cmd_handle, error_code, int_value, str_value);
}

void cb_enum_f7b70e00(unsigned int cmd_handle, unsigned int error_code, vcx_state_t enum_value) {
	callback_enumF7B70E00(cmd_handle, error_code, enum_value);
}

void cb_error_code_438abeb5(unsigned int cmd_handle, unsigned int error_code) {
	callback_error_code438ABEB5(cmd_handle, error_code);
}

