// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 29 Oct 2018 22:41:05 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "vcx.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// cb_string_ebc8845d is a proxy for callback cb_string.
void cb_string_ebc8845d(unsigned int cmd_handle, unsigned int error_code, char* str_value);

// cb_int_a42ee42d is a proxy for callback cb_int.
void cb_int_a42ee42d(unsigned int cmd_handle, unsigned int error_code, unsigned int int_value);

// cb_int_string_f8ca4bd5 is a proxy for callback cb_int_string.
void cb_int_string_f8ca4bd5(unsigned int cmd_handle, unsigned int error_code, unsigned int int_value, char* str_value);

// cb_enum_f7b70e00 is a proxy for callback cb_enum.
void cb_enum_f7b70e00(unsigned int cmd_handle, unsigned int error_code, vcx_state_t enum_value);

// cb_error_code_438abeb5 is a proxy for callback cb_error_code.
void cb_error_code_438abeb5(unsigned int cmd_handle, unsigned int error_code);

