// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 29 Oct 2018 22:41:05 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package vcx

/*
#cgo LDFLAGS: -lvcx
#include "vcx.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// State_t as declared in vcx/vcx.h:33
type State_t int32

// State_t enumeration from vcx/vcx.h:33
const ()

// Proof_state_t as declared in vcx/vcx.h:40
type Proof_state_t int32

// Proof_state_t enumeration from vcx/vcx.h:40
const ()
