// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 29 Oct 2018 22:41:05 IST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package vcx

/*
#cgo LDFLAGS: -lvcx
#include "vcx.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Error_t type as declared in vcx/vcx.h:8
type Error_t uint32

// Schema_handle_t type as declared in vcx/vcx.h:9
type Schema_handle_t uint32

// Credentialdef_handle_t type as declared in vcx/vcx.h:10
type Credentialdef_handle_t uint32

// Issuer_credential_handle_t type as declared in vcx/vcx.h:11
type Issuer_credential_handle_t uint32

// Disclosed_proof_handle_t type as declared in vcx/vcx.h:12
type Disclosed_proof_handle_t uint32

// Connection_handle_t type as declared in vcx/vcx.h:13
type Connection_handle_t uint32

// Credential_handle_t type as declared in vcx/vcx.h:14
type Credential_handle_t uint32

// Proof_handle_t type as declared in vcx/vcx.h:15
type Proof_handle_t uint32

// Command_handle_t type as declared in vcx/vcx.h:16
type Command_handle_t uint32

// Payment_handle_t type as declared in vcx/vcx.h:17
type Payment_handle_t uint32

// Wallet_search_handle_t type as declared in vcx/vcx.h:18
type Wallet_search_handle_t uint32

// Bool_t type as declared in vcx/vcx.h:19
type Bool_t uint32

// Price_t type as declared in vcx/vcx.h:21
type Price_t uint

// Callback_string type as declared in vcx/vcx.h:42
type Callback_string func(Cmd_handle Command_handle_t, Error_code Error_t, Str_value string)

// Callback_int type as declared in vcx/vcx.h:43
type Callback_int func(Cmd_handle Command_handle_t, Error_code Error_t, Int_value uint32)

// Callback_int_string type as declared in vcx/vcx.h:44
type Callback_int_string func(Cmd_handle Command_handle_t, Error_code Error_t, Int_value uint32, Str_value string)

// Callback_enum type as declared in vcx/vcx.h:45
type Callback_enum func(Cmd_handle Command_handle_t, Error_code Error_t, Enum_value State_t)

// Callback_error_code type as declared in vcx/vcx.h:46
type Callback_error_code func(Cmd_handle Command_handle_t, Error_code Error_t)
